Config = Config or {}

Config.Verses = {
    {
        title = 'Stillness',
        theme = 'Peace',
        reference = 'Psalm 46:10',
        text = 'Be still, and know that I am God.',
    },
    {
        title = 'Held By God',
        theme = 'Strength',
        reference = 'Isaiah 41:10',
        text = 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.',
    },
    {
        title = 'A Future With Hope',
        theme = 'Hope',
        reference = 'Jeremiah 29:11',
        text = 'For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.',
    },
    {
        title = 'Strength Through Christ',
        theme = 'Courage',
        reference = 'Philippians 4:13',
        text = 'I can do all things through Christ which strengtheneth me.',
    },
    {
        title = 'Be Strong',
        theme = 'Courage',
        reference = 'Joshua 1:9',
        text = 'Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.',
    },
    {
        title = 'Trust His Path',
        theme = 'Guidance',
        reference = 'Proverbs 3:5-6',
        text = 'Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.',
    },
    {
        title = 'The Shepherd',
        theme = 'Comfort',
        reference = 'Psalm 23:1',
        text = 'The LORD is my shepherd; I shall not want.',
    },
    {
        title = 'All Things For Good',
        theme = 'Hope',
        reference = 'Romans 8:28',
        text = 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.',
    },
    {
        title = 'Rest For The Weary',
        theme = 'Rest',
        reference = 'Matthew 11:28',
        text = 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
    },
    {
        title = 'Peace From Christ',
        theme = 'Peace',
        reference = 'John 14:27',
        text = 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.',
    },
    {
        title = 'He Delivers',
        theme = 'Comfort',
        reference = 'Psalm 34:17',
        text = 'The righteous cry, and the LORD heareth, and delivereth them out of all their troubles.',
    },
    {
        title = 'Morning Mercies',
        theme = 'Hope',
        reference = 'Lamentations 3:22-23',
        text = 'It is of the LORD\'S mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.',
    },
    {
        title = 'A Sound Mind',
        theme = 'Strength',
        reference = '2 Timothy 1:7',
        text = 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.',
    },
    {
        title = 'Lay It Down',
        theme = 'Rest',
        reference = 'Psalm 55:22',
        text = 'Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.',
    },
    {
        title = 'Overflowing Hope',
        theme = 'Hope',
        reference = 'Romans 15:13',
        text = 'Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.',
    },
    {
        title = 'Help From Above',
        theme = 'Comfort',
        reference = 'Psalm 121:1-2',
        text = 'I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth.',
    },
    {
        title = 'Renewed Strength',
        theme = 'Strength',
        reference = 'Isaiah 40:31',
        text = 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.',
    },
    {
        title = 'He Goes Before You',
        theme = 'Guidance',
        reference = 'Deuteronomy 31:8',
        text = 'And the LORD, he it is that doth go before thee; he will be with thee, he will not fail thee, neither forsake thee: fear not, neither be dismayed.',
    },
    {
        title = 'Light And Salvation',
        theme = 'Courage',
        reference = 'Psalm 27:1',
        text = 'The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?',
    },
    {
        title = 'He Cares For You',
        theme = 'Comfort',
        reference = '1 Peter 5:7',
        text = 'Casting all your care upon him; for he careth for you.',
    },
    {
        title = 'Cheer In Trouble',
        theme = 'Peace',
        reference = 'John 16:33',
        text = 'These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.',
    },
    {
        title = 'Hopeful Prayer',
        theme = 'Hope',
        reference = 'Romans 12:12',
        text = 'Rejoicing in hope; patient in tribulation; continuing instant in prayer.',
    },
    {
        title = 'Never Forsaken',
        theme = 'Comfort',
        reference = 'Hebrews 13:5',
        text = 'Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee.',
    },
    {
        title = 'Heart\'s Desire',
        theme = 'Joy',
        reference = 'Psalm 37:4',
        text = 'Delight thyself also in the LORD; and he shall give thee the desires of thine heart.',
    },
    {
        title = 'Peace Beyond Understanding',
        theme = 'Peace',
        reference = 'Philippians 4:6-7',
        text = 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.',
    },
    {
        title = 'Stronghold In Trouble',
        theme = 'Strength',
        reference = 'Nahum 1:7',
        text = 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.',
    },
    {
        title = 'My Defence',
        theme = 'Strength',
        reference = 'Psalm 62:6',
        text = 'He only is my rock and my salvation: he is my defence; I shall not be moved.',
    },
    {
        title = 'Every Good Gift',
        theme = 'Joy',
        reference = 'James 1:17',
        text = 'Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning.',
    },
    {
        title = 'Rejoiced Over',
        theme = 'Love',
        reference = 'Zephaniah 3:17',
        text = 'The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.',
    },
    {
        title = 'Joy In The Morning',
        theme = 'Hope',
        reference = 'Psalm 30:5',
        text = 'For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.',
    }
}
